name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: docker build
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     push: true
      #     tags: |
      #         ghcr.io/${{ github.repository }}:latest
      #         ghcr.io/${{ github.repository }}:${{ github.sha }}


      # - name: Update image tag in Helm chart
      #   shell: bash
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITOPS_PAT }}
      #   run: |
      #     # Configure git credential store
      #     git config --global credential.helper store
      #     echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
      #     # Remove any existing gitops directory
      #     rm -rf gitops
          
      #     # Clone repository using HTTPS URL without token
      #     git clone https://github.com/yagen1111/helm-web-db.git gitops
      #     cd gitops

      #     sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|g" values.yaml
  
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"
      #     git add values.yaml
      #     git commit -m "Update image to ${{ github.sha }}"
          
      #     # Push
      #     git push -f https://${GIT_TOKEN}@github.com/yagen1111/helm-web-db.git main